# ============================================================================
# Python CI Pipeline Template (Modular)
# ============================================================================
# Copy this to your project's .github/workflows/ci.yml
#
# Jobs (run in parallel):
#   1. lint      — ruff linter with GitHub annotations
#   2. typecheck — mypy static type analysis
#   3. test      — pytest with coverage (multi-version matrix)
#   4. scan      — placeholder for project-specific scans (PII, custom)
#
# Customize:
#   - Python versions in test matrix
#   - ruff rules in [tool.ruff] section of pyproject.toml
#   - mypy config in [tool.mypy] section of pyproject.toml
#   - Add project-specific scan commands to the scan job
#
# Requires: pyproject.toml (see cicd/pyproject-template.toml)
# ============================================================================

name: Python CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint with ruff
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    
    - name: Run ruff linter
      run: |
        ruff check . --output-format=github

  typecheck:
    name: Type check with mypy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install mypy
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    
    - name: Run mypy type checker
      run: |
        mypy . --ignore-missing-imports
      continue-on-error: true

  test:
    name: Test with pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests with coverage
      run: |
        pytest tests/ --cov=. --cov-report=xml --cov-report=term-missing -v
    
    - name: Upload coverage reports
      if: matrix.python-version == '3.12'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: coverage.xml
        retention-days: 30

  scan:
    name: Custom project scans
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Run custom scans
      run: |
        # Add project-specific scans here. Examples:
        # python scripts/pii_scanner.py  # PII/secrets scan
        # python -m safety check          # Dependency vulnerability scan
        echo "No custom scans configured. Add your scan commands here."

  ci-summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [lint, typecheck, test, scan]
    if: always()
    
    steps:
    - name: Generate summary
      run: |
        echo "## CI Pipeline Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Lint | ${{ needs.lint.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Type Check | ${{ needs.typecheck.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Test | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Scan | ${{ needs.scan.result }} |" >> $GITHUB_STEP_SUMMARY
