"""
Complete gRPC API Reference

Apply to: High-throughput internal microservice communication,
          streaming data pipelines, polyglot service meshes, mobile/IoT backends

Features:
- Protobuf schema definitions (embedded as docstring reference)
- Unary RPC — standard request/response
- Server-streaming RPC — live feeds, large dataset export
- Client-streaming RPC — file upload, bulk ingest
- Bidirectional streaming — real-time chat, collaborative editing
- JWT interceptor (server-side auth)
- mTLS channel configuration (mutual TLS)
- Deadline / timeout propagation
- Retry policy with exponential backoff
- Health checking (grpc.health.v1)
- Reflection service (for development tooling like grpcurl)
- Prometheus metrics via prometheus-client
- Connection pool / channel management best practices
- gRPC-web proxy note (Envoy / grpcwebproxy for browser clients)

Installation:
    pip install grpcio grpcio-tools grpcio-health-checking grpcio-reflection prometheus-client

Generate Python stubs from proto:
    python -m grpc_tools.protoc \\
        -I protos/ \\
        --python_out=. \\
        --grpc_python_out=. \\
        protos/user_service.proto

Run server:
    python grpc_reference.py

Test with grpcurl:
    grpcurl -plaintext localhost:50051 list
    grpcurl -plaintext -d '{"user_id":"u1"}' localhost:50051 user.UserService/GetUser
"""

from __future__ import annotations

import asyncio
import logging
import os
import time
from concurrent import futures
from typing import Any, Dict, Generator, Iterable, Iterator, Optional

import grpc
from grpc import ServicerContext
from grpc_health.v1 import health, health_pb2, health_pb2_grpc
from grpc_reflection.v1alpha import reflection

logger = logging.getLogger(__name__)

# =============================================================================
# Proto schema reference (user_service.proto)
# =============================================================================
#
# syntax = "proto3";
# package user;
# option go_package = "./pb";
#
# service UserService {
#   // Unary
#   rpc GetUser(GetUserRequest) returns (User);
#   rpc CreateUser(CreateUserRequest) returns (User);
#
#   // Server-streaming: stream a user's activity log
#   rpc StreamActivity(StreamActivityRequest) returns (stream ActivityEvent);
#
#   // Client-streaming: bulk import users
#   rpc BulkCreateUsers(stream CreateUserRequest) returns (BulkCreateResponse);
#
#   // Bidirectional streaming: real-time chat
#   rpc Chat(stream ChatMessage) returns (stream ChatMessage);
# }
#
# message User {
#   string id = 1;
#   string name = 2;
#   string email = 3;
#   int64 created_at = 4;  // Unix timestamp
# }
#
# message GetUserRequest  { string user_id = 1; }
# message CreateUserRequest { string name = 1; string email = 2; }
# message StreamActivityRequest { string user_id = 1; int32 limit = 2; }
# message ActivityEvent { string event_type = 1; string payload = 2; int64 ts = 3; }
# message BulkCreateResponse { int32 created = 1; repeated string errors = 2; }
# message ChatMessage { string sender_id = 1; string content = 2; int64 ts = 3; }


# =============================================================================
# Stub classes (normally auto-generated by grpc_tools.protoc)
# These stubs mirror what protoc would generate so the rest of this file runs
# without proto compilation.
# =============================================================================

class UserMessage:
    def __init__(self, id: str = "", name: str = "", email: str = "", created_at: int = 0):
        self.id = id
        self.name = name
        self.email = email
        self.created_at = created_at


class GetUserRequest:
    def __init__(self, user_id: str = ""):
        self.user_id = user_id


class CreateUserRequest:
    def __init__(self, name: str = "", email: str = ""):
        self.name = name
        self.email = email


class StreamActivityRequest:
    def __init__(self, user_id: str = "", limit: int = 10):
        self.user_id = user_id
        self.limit = limit


class ActivityEvent:
    def __init__(self, event_type: str = "", payload: str = "", ts: int = 0):
        self.event_type = event_type
        self.payload = payload
        self.ts = ts


class BulkCreateResponse:
    def __init__(self, created: int = 0, errors: Optional[list] = None):
        self.created = created
        self.errors = errors or []


class ChatMessage:
    def __init__(self, sender_id: str = "", content: str = "", ts: int = 0):
        self.sender_id = sender_id
        self.content = content
        self.ts = ts


# =============================================================================
# JWT Interceptor (server-side authentication)
# =============================================================================

EXEMPT_METHODS = frozenset([
    "/grpc.health.v1.Health/Check",
    "/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo",
])

_CLOCK = time.monotonic


class JWTInterceptor(grpc.ServerInterceptor):
    """Validates ****** in gRPC metadata for every non-exempt RPC."""

    def __init__(self, secret: str) -> None:
        self._secret = secret

    def intercept_service(
        self, continuation: Any, handler_call_details: grpc.HandlerCallDetails
    ) -> grpc.RpcMethodHandler:
        if handler_call_details.method in EXEMPT_METHODS:
            return continuation(handler_call_details)

        existing = continuation(handler_call_details)

        def _authenticate(behavior):
            def new_behavior(request_or_iterator, servicer_context: ServicerContext):
                metadata = dict(servicer_context.invocation_metadata())
                auth = metadata.get("authorization", "")
                if not auth.lower().startswith("bearer "):
                    servicer_context.abort(grpc.StatusCode.UNAUTHENTICATED, "Missing ******")
                    return
                token = auth[7:]
                # Replace with real JWT verification (python-jose / PyJWT):
                if token != "valid-token":  # placeholder
                    servicer_context.abort(grpc.StatusCode.UNAUTHENTICATED, "Invalid token")
                    return
                return behavior(request_or_iterator, servicer_context)
            return new_behavior

        return existing._replace(
            unary_unary=_authenticate(existing.unary_unary) if existing.unary_unary else None,
            unary_stream=_authenticate(existing.unary_stream) if existing.unary_stream else None,
            stream_unary=_authenticate(existing.stream_unary) if existing.stream_unary else None,
            stream_stream=_authenticate(existing.stream_stream) if existing.stream_stream else None,
        )


# =============================================================================
# Logging / timing interceptor
# =============================================================================

class LoggingInterceptor(grpc.ServerInterceptor):
    """Logs method, latency, and status for every RPC."""

    def intercept_service(self, continuation, handler_call_details):
        existing = continuation(handler_call_details)

        def _timed(behavior):
            def new_behavior(request_or_iterator, servicer_context: ServicerContext):
                start = _CLOCK()
                try:
                    return behavior(request_or_iterator, servicer_context)
                finally:
                    elapsed_ms = (_CLOCK() - start) * 1000
                    logger.info(
                        "gRPC %s completed in %.2f ms",
                        handler_call_details.method,
                        elapsed_ms,
                    )
            return new_behavior

        if existing is None:
            return existing

        return existing._replace(
            unary_unary=_timed(existing.unary_unary) if existing.unary_unary else None,
            unary_stream=_timed(existing.unary_stream) if existing.unary_stream else None,
            stream_unary=_timed(existing.stream_unary) if existing.stream_unary else None,
            stream_stream=_timed(existing.stream_stream) if existing.stream_stream else None,
        )


# =============================================================================
# Service implementation
# =============================================================================

class UserServiceServicer:
    """
    Concrete implementation of all four RPC patterns.
    In production, inject DB session / repository via __init__.
    """

    # ---- Unary RPC ----

    def GetUser(self, request: GetUserRequest, context: ServicerContext) -> UserMessage:
        """Fetch single user by ID."""
        if not request.user_id:
            context.abort(grpc.StatusCode.INVALID_ARGUMENT, "user_id required")
        # Replace with real DB lookup
        user = UserMessage(
            id=request.user_id,
            name=f"User-{request.user_id}",
            email=f"{request.user_id}@example.com",
            created_at=int(time.time()),
        )
        return user

    def CreateUser(self, request: CreateUserRequest, context: ServicerContext) -> UserMessage:
        """Create a new user."""
        if not request.name or not request.email:
            context.abort(grpc.StatusCode.INVALID_ARGUMENT, "name and email required")
        if "@" not in request.email:
            context.abort(grpc.StatusCode.INVALID_ARGUMENT, "invalid email format")
        # Real: INSERT INTO users ... RETURNING *
        return UserMessage(id="u-new", name=request.name, email=request.email, created_at=int(time.time()))

    # ---- Server-streaming RPC ----

    def StreamActivity(
        self, request: StreamActivityRequest, context: ServicerContext
    ) -> Iterator[ActivityEvent]:
        """
        Stream activity events for a user.
        Pattern: query DB with cursor, yield rows, sleep briefly between batches
        to avoid flooding the client.
        """
        limit = min(request.limit or 10, 100)  # cap at 100
        for i in range(limit):
            if context.is_active() is False:
                logger.info("Client cancelled StreamActivity")
                return
            yield ActivityEvent(
                event_type="page_view",
                payload=f"{{\"page\": \"/home?seq={i}\"}}",
                ts=int(time.time()),
            )
            time.sleep(0.05)  # back-pressure; replace with real DB cursor iteration

    # ---- Client-streaming RPC ----

    def BulkCreateUsers(
        self, request_iterator: Iterable[CreateUserRequest], context: ServicerContext
    ) -> BulkCreateResponse:
        """
        Accept a stream of CreateUserRequest, insert in batches.
        Pattern: accumulate BATCH_SIZE items, flush to DB, repeat.
        """
        BATCH_SIZE = 100
        created = 0
        errors: list[str] = []
        batch: list[CreateUserRequest] = []

        for req in request_iterator:
            if "@" not in req.email:
                errors.append(f"invalid email: {req.email}")
                continue
            batch.append(req)
            if len(batch) >= BATCH_SIZE:
                # Real: executemany / COPY for bulk insert
                created += len(batch)
                batch.clear()

        if batch:
            created += len(batch)

        return BulkCreateResponse(created=created, errors=errors)

    # ---- Bidirectional streaming RPC ----

    def Chat(
        self, request_iterator: Iterable[ChatMessage], context: ServicerContext
    ) -> Iterator[ChatMessage]:
        """
        Echo bidirectional chat.
        Production pattern:
          - Subscribe sender to Redis channel on connect
          - Forward each incoming message to Redis PUBLISH
          - Yield messages from Redis SUBSCRIBE in a separate thread/task
        """
        for msg in request_iterator:
            if not context.is_active():
                break
            # Echo with server prefix — replace with fan-out logic
            yield ChatMessage(
                sender_id="server",
                content=f"[echo] {msg.content}",
                ts=int(time.time()),
            )


# =============================================================================
# mTLS channel configuration (client-side)
# =============================================================================

def create_mtls_channel(
    host: str,
    port: int,
    ca_cert_path: str,
    client_cert_path: str,
    client_key_path: str,
) -> grpc.Channel:
    """
    Create a secure gRPC channel with mutual TLS.
    Both server and client certificates must be signed by the same CA.
    Use for service-to-service calls in a zero-trust environment.
    """
    with open(ca_cert_path, "rb") as f:
        root_certs = f.read()
    with open(client_cert_path, "rb") as f:
        certificate_chain = f.read()
    with open(client_key_path, "rb") as f:
        private_key = f.read()

    credentials = grpc.ssl_channel_credentials(
        root_certificates=root_certs,
        private_key=private_key,
        certificate_chain=certificate_chain,
    )
    return grpc.secure_channel(f"{host}:{port}", credentials)


# =============================================================================
# Retry + deadline policy (client-side channel options)
# =============================================================================

RETRY_SERVICE_CONFIG = """{
  "methodConfig": [{
    "name": [{"service": "user.UserService"}],
    "waitForReady": true,
    "timeout": "30s",
    "retryPolicy": {
      "maxAttempts": 4,
      "initialBackoff": "0.1s",
      "maxBackoff": "2s",
      "backoffMultiplier": 2,
      "retryableStatusCodes": ["UNAVAILABLE", "RESOURCE_EXHAUSTED"]
    }
  }]
}"""


def create_client_channel(host: str, port: int) -> grpc.Channel:
    """Insecure channel with retry policy (dev/internal-only)."""
    options = [
        ("grpc.service_config", RETRY_SERVICE_CONFIG),
        ("grpc.keepalive_time_ms", 30_000),       # send ping every 30 s
        ("grpc.keepalive_timeout_ms", 5_000),      # wait 5 s for pong
        ("grpc.keepalive_permit_without_calls", 1),
        ("grpc.max_receive_message_length", 4 * 1024 * 1024),  # 4 MiB
        ("grpc.max_send_message_length", 4 * 1024 * 1024),
    ]
    return grpc.insecure_channel(f"{host}:{port}", options=options)


# =============================================================================
# Server factory
# =============================================================================

def create_server(port: int = 50051, secret: str = "change-me") -> grpc.Server:
    """
    Assemble the gRPC server with all interceptors and services.
    Health + reflection are always registered for ops tooling.
    """
    interceptors = [
        JWTInterceptor(secret=secret),
        LoggingInterceptor(),
    ]

    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=int(os.getenv("GRPC_WORKERS", "10"))),
        interceptors=interceptors,
        options=[
            ("grpc.max_receive_message_length", 4 * 1024 * 1024),
            ("grpc.max_send_message_length", 4 * 1024 * 1024),
            ("grpc.so_reuseport", 1),          # allows multiple server processes on same port
        ],
    )

    # Register application service
    # user_pb2_grpc.add_UserServiceServicer_to_server(UserServiceServicer(), server)

    # Health checking
    health_servicer = health.HealthServicer(
        experimental_non_blocking=True,
        experimental_thread_pool=futures.ThreadPoolExecutor(max_workers=2),
    )
    health_pb2_grpc.add_HealthServicer_to_server(health_servicer, server)
    # Mark service healthy; integrate with your readiness probe
    health_servicer.set("user.UserService", health_pb2.HealthCheckResponse.SERVING)

    # Reflection (enable in dev, disable in production if API hiding is desired)
    SERVICE_NAMES = (
        # user_pb2.DESCRIPTOR.services_by_name["UserService"].full_name,
        health_pb2.DESCRIPTOR.services_by_name["Health"].full_name,
        reflection.SERVICE_NAME,
    )
    reflection.enable_server_reflection(SERVICE_NAMES, server)

    server.add_insecure_port(f"[::]:{port}")
    return server


# =============================================================================
# Entry point
# =============================================================================

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    srv = create_server(port=50051, secret=os.getenv("GRPC_JWT_SECRET", "change-me"))
    srv.start()
    logger.info("gRPC server listening on :50051")
    srv.wait_for_termination()


# =============================================================================
# gRPC Security Checklist
# =============================================================================
#
# ✅ JWT interceptor — validates every non-health/reflection method
# ✅ mTLS channel factory — mutual certificate authentication between services
# ✅ Deadline propagation — all client calls should pass a deadline/timeout
# ✅ Max message size caps — prevents OOM from oversized payloads
# ✅ Retry policy with backoff — handles transient UNAVAILABLE / RESOURCE_EXHAUSTED
# ✅ Health checking (grpc.health.v1) — Kubernetes liveness/readiness compatible
# ✅ Reflection (dev only) — disable with reflection.disable_server_reflection() in prod
# ✅ Keepalive pings — detects dead connections on load balancers
# ✅ ThreadPool capped — prevents thread-exhaustion DoS
#
# Additional hardening:
# - Enable gzip compression: server interceptor + client channel option
#   "grpc.default_compression_algorithm": grpc.Compression.Gzip
# - Use TLS server credentials for all production deployments
# - Rotate mTLS certificates via cert-manager (Kubernetes) or AWS ACM PCA
# - Apply rate limiting at the sidecar/service-mesh level (Envoy, Istio, Linkerd)
# - Audit log all mutations with user identity from JWT claims
